-----20/09/2015 12:48
Unable to add code to mapping:
Traceback (most recent call last):
  File "C:\Users\cekin\Documents\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 174, in exclude_tfc
    result = sql.exclude_tfc(system,tfc,exclusion,user.email)
AttributeError: 'str' object has no attribute 'email'
-----20/09/2015 12:49
Unable to add code to mapping:
Traceback (most recent call last):
  File "C:\Users\cekin\Documents\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 174, in exclude_tfc
    result = sql.exclude_tfc(system,tfc,exclusion,user.email)
AttributeError: 'str' object has no attribute 'email'
-----20/09/2015 12:53
Unable to add code to mapping:
Traceback (most recent call last):
  File "C:\Users\cekin\Documents\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 174, in exclude_tfc
    raise Exception('message')
Exception: message
-----21/09/2015 00:41
Error getting global codes together:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 102, in global_table
    L['result'].append([r['GlobalCode'], r['Description'], r['Sample'], r['Type'], r['Analyte'], r['PrimaryLibrary'], r['SubSection'], r['Department']])
TypeError: string indices must be integers, not str
-----01/10/2015 18:48
Error looking up TLC detail:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 100, in system_info
    result = sql.exec_stored_procedure('spGlobalsApp_SystemOverview', [system,section])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Could not find stored procedure 'spGlobalsApp_SystemOverview'. (2812) (SQLExecDirectW)")
-----07/10/2015 23:32
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:33
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:36
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:37
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:37
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:38
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:38
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('08004', '[08004] [Microsoft][ODBC SQL Server Driver][SQL Server]The server principal "TDLPATHOLOGY\\cekin" is not able to access the database "RFH_BIO_DW" under the current security context. (916) (SQLExecDirectW)')
-----07/10/2015 23:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:48
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 21, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:48
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 21, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----07/10/2015 23:50
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 218, in dashboard
    data = sql.exec_stored_procedure('spGlobalsApp_AllSystemStats')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 21, in exec_stored_procedure
    cursor.execute(sql)
Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
-----23/10/2015 17:10
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 221, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----23/10/2015 17:11
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 221, in dashboard
    for row in data:
TypeError: string indices must be integers, not str
-----23/10/2015 17:12
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 222, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----23/10/2015 17:20
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', None, True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 35, in exec_stored_procedure_list
    for a in arguements:
TypeError: 'NoneType' object is not iterable
-----23/10/2015 17:21
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', [], True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 35, in exec_stored_procedure_list
    for a in arguements:
TypeError: 'NoneType' object is not iterable
-----23/10/2015 17:21
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', [], True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 35, in exec_stored_procedure_list
    for a in arguements:
TypeError: 'NoneType' object is not iterable
-----23/10/2015 17:22
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:22
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:23
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:24
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 53, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----23/10/2015 17:27
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 248, in globalseditor
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', header_row=True)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 54, in exec_stored_procedure_list
    print 'Problem with ', raw_data[i][j]
  File "C:\Anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 8: character maps to <undefined>
-----25/10/2015 10:17
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 260, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', arguements=[department], header_row=False)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 45, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:18
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 260, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', arguements=[department], header_row=False)
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:22
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor', [department])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:23
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 45, in exec_stored_procedure_list
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Procedure or function 'spGlobalsApp_GlobalEditor' expects parameter '@department', which was not supplied. (201) (SQLExecDirectW)")
-----25/10/2015 10:24
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:31
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:50
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:52
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 10:53
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 46, in exec_stored_procedure_list
    raw_data = cursor.fetchall()
ProgrammingError: No results.  Previous SQL was not a query.
-----25/10/2015 11:47
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in globalseditordata
    result = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor',[department])
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 41, in exec_stored_procedure_list
    sql = "EXEC %s %s;" % (stored_procedure,','.join(args))
TypeError: sequence item 0: expected string, NoneType found
-----25/10/2015 22:59
Error executing spGlobalsApp_GlobalEditor_DeptList:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 290, in globals_department_list
    departments = sql.exec_stored_procedure_list('spGlobalsApp_GlobalEditor_DeptList')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 45, in exec_stored_procedure_list
    cursor.execute(sql)
ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Could not find stored procedure 'spGlobalsApp_GlobalEditor_DeptList'. (2812) (SQLExecDirectW)")
-----25/10/2015 23:21
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 282, in pull_all_tfcs_to_one_table
    result = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_LoadAllTFCs')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    headers = [column[0] for column in cursor.description]
TypeError: 'NoneType' object is not iterable
-----25/10/2015 23:23
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 282, in pull_all_tfcs_to_one_table
    result = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_LoadAllTFCs')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    headers = [column[0] for column in cursor.description]
TypeError: 'NoneType' object is not iterable
-----25/10/2015 23:25
Error executing spGlobalsApp_GlobalEditor:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 282, in pull_all_tfcs_to_one_table
    result = sql.exec_stored_procedure('spGlobalsApp_GlobalCodeDetail_LoadAllTFCs')
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\sql.py", line 19, in exec_stored_procedure
    headers = [column[0] for column in cursor.description]
TypeError: 'NoneType' object is not iterable
-----26/10/2015 20:14
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:15
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:16
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:20
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:22
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:25
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:25
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:28
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:29
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:31
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:32
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:33
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:34
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:35
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:36
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:38
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:40
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:40
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:40
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:41
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:42
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:42
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:51
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:53
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:53
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:53
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:55
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 20:55
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 252, in dashboard
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:01
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 262, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:01
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 262, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:02
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:03
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:04
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:05
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:06
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:06
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 261, in dashboard_getdata
    for row in data:
NameError: global name 'data' is not defined
-----26/10/2015 21:07
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 262, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:09
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 263, in dashboard_getdata
    if row['System'] not in D:
TypeError: string indices must be integers, not str
-----26/10/2015 21:27
Error getting dashboard data:
Traceback (most recent call last):
  File "\\tdlpathology\docs\TDL\IT\Chris Ekin\GitHub\Global_Codes_App\Global Codes App\Global_Codes_App\views.py", line 266, in dashboard_getdata
    summary[system][0] += row[2]
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
